//#define _CRT_SECURE_NO_WARNINGS 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include <iostream>
#include <windows.h>
using namespace std;
#include <string>
#include <cctype>
#include <ctime>
#define SIZE 256
#define ASCENT_BRANCH "RS-FUNSERVER"
int g_revision = 0;
int g_oldRevision = -1;

int main(int argc, char* argv[])
{

	char acUserName[100];
	DWORD nUserName = sizeof(acUserName);
	GetUserName(acUserName, &nUserName);

	char acComputerName[100];
	DWORD nComputerName = sizeof(acComputerName);
	GetComputerName(acComputerName, &nComputerName);

	char buffer[SIZE];

	time_t curtime;
	struct tm *loctime;   
	struct tm *utctime;

	FILE * pFile = fopen("../.svn/entries", "r");
	printf("SVN Revision Extractor\n");
	printf("Written by Burlex, 2008/02/20\n");
	printf("Modified by Midnight, 2-23-2008\n");
	printf("Branch: %s\n", ASCENT_BRANCH);
	/* Get the current time. */
	curtime = time(NULL);

	/* Convert it to local time representation. */
	loctime = localtime(&curtime);
	utctime = gmtime(&curtime);

	if( pFile == NULL )
	{
		printf("Could not open entries file. This may not be a SVN checkout? Assuming revision 0.\n");
		return 1;
	}
	else
	{
		char * p;
		char * q;
		char * buffer;
		long sz;

		fseek( pFile, 0, SEEK_END );
		sz = ftell( pFile );
		fseek( pFile, 0, SEEK_SET );

		buffer = (char*)malloc( sz );
		if( buffer != NULL )
		{
			fread( buffer, sz, 1, pFile );

			p = strstr( buffer, "dir" );
			if( p != NULL )
			{
				while( !isdigit( *p ) )
					++p;

				q = p;
				while( isdigit( *q ) )
					++q;

				*q = 0;

				g_revision = atoi( p );
				printf("Revision found: %u\n", g_revision);
			}

			free( buffer );
		}

		fclose ( pFile );
		printf("Opening existing file...\n");
		
		pFile = fopen("svn_revision.h", "r");
		if( pFile != NULL )
		{
			fseek( pFile, 0, SEEK_END );
			sz = ftell( pFile );
			fseek( pFile, 0, SEEK_SET );

			buffer = (char*)malloc( sz );
			if( buffer != NULL )
			{
				fread( buffer, sz, 1, pFile );
				p = strstr( buffer, "BUILD_REVISION =");
				if( p != NULL )
				{
					while( !isdigit( *p ) )
						++p;

					q = p;
					while( isdigit( *q ) )
						++q;

					*q = 0;

					g_oldRevision = atoi( p );
				}

				free( buffer );
			}

			fclose( pFile );
		}
	}

	if( g_oldRevision == g_revision )
	{
		printf("Revisions match exiting file. Skipping.\n");
		return 0;
	}

	printf("Writing output file...\n");
	
	pFile = fopen( "svn_revision.h", "w" );
	if( pFile == NULL )
	{
		printf("Output file could not be opened.\n");
		return 2;
	}
	else
	{
		fprintf(pFile, "// This file was automatically generated by the SVN revision extractor.\n");
		fprintf(pFile, "// There is no need to modify it.\n");
		fprintf(pFile, "#ifndef SVN_REVISION_H\n");
		fprintf(pFile, "#define SVN_REVISION_H\n\n");
		fprintf(pFile, "static const char * BUILD_TAG = \"%s\";\n", ASCENT_BRANCH);
		fprintf(pFile, "static int BUILD_REVISION = %u;\n\n", g_revision);
		fprintf(pFile, "#define BUILD_USER \"%s\"\n", acUserName);
		fprintf(pFile, "#define BUILD_WORKSTATION \"%s\"\n", acComputerName);
		strftime (buffer, SIZE, "#define SVN_DATE \"%A, %B %d %Y\"\n", loctime);
		fprintf( pFile, buffer );
		fprintf(pFile, "\n");
		strftime (buffer, SIZE, "#define BUILD_TIME \"%I:%M%p (UTC)\"\n", utctime);
		fprintf( pFile, buffer );
		strftime (buffer, SIZE, "#define BUILD_DATE \"%b %d %Y\"\n", loctime);
		fprintf( pFile, buffer );
		fprintf(pFile, "\n");
		fprintf(pFile, "#endif\t\t // SVN_REVISION_H\n\n");
		fflush( pFile );
		fclose( pFile );

		printf("Output file written. Exiting cleanly.\n");
	}
	return 0;
}
